#! /bin/sh
# Creates tarball, uploads to Rapidshare, and posts to Reddit.
# All parameters below are necessary  

while getopts ":a:b:c:d:h:l:s:p:" opt; do
    case $opt in
        a)
            rapid_username=$OPTARG;;
        b)
            rapid_password=$OPTARG;;
        c)
            reddit_username=$OPTARG;;
        d) 
            reddit_password=$OPTARG;;
        h)
            host=$OPTARG;;
        l)
            download_dir=$OPTARG;;
        s)
            subreddit=$OPTARG;;
        p)
            python_dir=$OPTARG;;
        \?)
            echo "Invalid option: -$OPTARG\n"
            echo "-a: rapidshare username\n"
            echo "-b: rapidshare pw\n"
            echo "-c: reddit username\n"
            echo "-d: reddit username\n"
            echo "-h: host url path to file\n"
            echo "-l: local path to file\n"
            echo "-s: subreddit to post to\n"
            echo "-p: python path\n"
            exit 1;;
        :)
            echo "OPTION -$OPTARG requires an argument"
            exit 1;;
    esac
done

cd $download_dir
date=`date +%F`                                        

# Gets all files from today and tarballs them
find -daystart -ctime 0 -not -name . -print0 | xargs -0 zip $date.zip --no-wild

# upload zip to rapidshare
links=`python "$python_dir"rapidshare.py -u $rapid_username -p $rapid_password -f "$host$date".zip`

# post link to reddit
post="Hi $subreddit,         
    
I'm prestobot, a set of scripts that scrapes the front page of a subreddit for youtube links. Everyday, I download music posted via Youtube on the front page. I compress all of these files together, upload them to Rapidshare (since they readily have an API, writing a Mediafire library is beyond my abilities), and post the download links to Reddit. You can use me for music discovery and consider these songs samplers. Support the artists you really enjoy by buying their albums. Here are today's currently hot songs.


==Links==          


$links"

python "${python_dir}reddit.py" -u $reddit_username -p $reddit_password -s $subreddit -k "self" -t "prestobot $date: download link for today's popular songs for $subreddit" -l "$post"

