#! /bin/sh
# Creates tarball, uploads to filevo, and posts to Reddit. Main method for whole process. 

while getopts ":a:b:c:d:h:l:s:p:" opt; do
    case $opt in
        a)
            rapid_username=$OPTARG;;
        b)
            rapid_password=$OPTARG;;
        c)
            reddit_username=$OPTARG;;
        d) 
            reddit_password=$OPTARG;;
        h)
            host=$OPTARG;;
        l)
            download_dir=$OPTARG;;
        s)
            subreddit=$OPTARG;;
        p)
            python_dir=$OPTARG;;
        \?)
            echo "Invalid option: -$OPTARG\n"
            echo "-a: rapidshare username\n"
            echo "-b: rapidshare pw\n"
            echo "-c: reddit username\n"
            echo "-d: reddit username\n"
            echo "-h: host url path to file\n"
            echo "-l: local path to file\n"
            echo "-s: subreddit to post to\n"
            echo "-p: python path\n"
            exit 1;;
        :)
            echo "OPTION -$OPTARG requires an argument"
            exit 1;;
    esac
done

cd $download_dir
date=`date +%F`                                        

# Gets all files from today and tarballs them
#find $download_dir -daystart -ctime 0 -not -wholename $download_dir -print0 | tar -cvf output.tar --no-wildcards --null -T -
find -daystart -ctime 0 -not -name . -print0 | xargs -0 zip $date.zip --no-wild

# upload zip to rapidshare
links=`python "${python_dir}uploadToRapidshare.py" -u $rapid_username -p $rapid_password -f $host$date.zip`

# post link to reddit
post="Hello $subreddit,    
My name is prestobot, a set of scripts that scrapes the front page of a subreddit for youtube links daily. I download these songs and convert them to .mp3. Then,  I zip all of these files together, upload them to Rapidshare, and post the download links to Reddit. My source code can be found at github.com/ngokevin/mp3-Suite. I am pleased to bring to you today's top songs for download.     

==Links==    

$links"

python "${python_dir}postToReddit.py" -u $reddit_username -p $reddit_password -s $subreddit -k "self" -t "prestobot $date: download link to today's top songs for $subreddit" -l $post

